repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
        args: [--pytest-test-first]
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix --force-exclude
        language: system
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude
        language: system
        types_or: [python, pyi, jupyter]
      - id: ty
        name: ty check
        entry: uv run ty check
        language: system
        pass_filenames: false
        require_serial: true
        always_run: true
